const AUDIT_ACTIONS = {
  LOGIN:          'LOGIN',
  LOGIN_FAILED:   'LOGIN_FAILED',
  LOGOUT:         'LOGOUT',
  REGISTER:       'REGISTER',
  DELETE_USER:    'DELETE_USER',
  CREATE_RECORD:  'CREATE_RECORD',
  UPDATE_RECORD:  'UPDATE_RECORD',
  DELETE_RECORD:  'DELETE_RECORD',
  RESTORE_RECORD: 'RESTORE_RECORD',
  UPDATE_STATUS:  'UPDATE_STATUS',
  UPDATE_ROLE:    'UPDATE_ROLE',
};

module.exports = AUDIT_ACTIONS;